# Generated by Django 4.2.1 on 2023-05-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('recipe_type', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], max_length=10)),
                ('alternate_name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('meat_type', models.CharField(max_length=20, null=True)),
                ('meat_classfication', models.CharField(max_length=20, null=True)),
                ('cuisine', models.CharField(max_length=50, null=True)),
                ('serving_quantity', models.CharField(max_length=20, null=True)),
                ('serves', models.CharField(max_length=10, null=True)),
                ('meal_type', models.CharField(max_length=30, null=True)),
                ('cookwares', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_cooking_steps', models.CharField(max_length=5000, null=True)),
                ('cooking_steps', models.CharField(max_length=5000, null=True)),
                ('tips', models.JSONField(default=dict, null=True)),
                ('total_duration', models.CharField(default='30', max_length=5, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
